### ISSUE TITLE
Missing support for x86_64 arch

### ISSUE THREAD

**Issue by christ776** [beyonderyue/ios-secp256k1#1]
Though I was able to make the script run as expected, Xcode is complaining that the x86_64 architecture is missing.
```
missing required architecture x86_64 in file /Users/christian/Documents/NetKi/netki-ios-sdk/secp256k1.framework/secp256k1 (4 slices)```

**Comment by christ776** [comment]
Just fixed it by adding the x86_64 architecture to the scripts.



[Archive.zip](https://github.com/beyonderyue/ios-secp256k1/files/1036871/Archive.zip)

**Comment by beyonderyue** [comment]
Thanks for your solution for this.
