### ISSUE TITLE
Bitcode support.

### ISSUE THREAD

**Issue by CikeQiu** [beyonderyue/ios-secp256k1#2]
Could you reply me，how can I build for bitcode？Thank you very much！

**Comment by beyonderyue** [comment]
please refer https://stackoverflow.com/questions/31233395/ios-library-to-bitcode
I don't have a MAC now, so I can't do a test, check it by yourself.

**Comment by CikeQiu** [comment]
OK, thank you very much.

**Comment by beyonderyue** [comment]
close
