### ISSUE TITLE
./configure not found with gitClone method

### ISSUE THREAD

**Issue by AmitShah** [beyonderyue/ios-secp256k1#6]
When running with new updates and git Clone, the configure script is not generated until after autogen.sh is run.  How to work around this?

/secp256k1.sh: line 94: ./configure: No such file or directory

**Comment by beyonderyue** [comment]
I add a work around for the git clone feature, refer the latest code
Thank you

**Comment by AmitShah** [comment]
Thanks! I had a pull request but you fixed it already :)
